### PR TITLE
Add support for Tales of Hearts DS

### PR DESCRIPTION
**Pull request by fortiersteven**
- Add a button to load Tales of Hearts DS new folder, last folder and desmume location
- Functionality of looking at menu, skits and story, save the files

**Regular tests**
- Saving file for Tales of Hearts should not update the xml format (just update english text and status)

**Integration tests**
- Should not break Tales of rebirth
- Make sure that saving files for Rebirht doesnt not mess the XML for menu, skits and story

### CODE REVIEW

**Comment by fortiersteven** [comment]
**Tests for Tales of Hearts DS**

- Making a modification to a story file
image
image

- Making a modification to a skit file
image
image

- Making a modificatio to a menu file
image
image

**Comment by fortiersteven** [comment]
**Tests for Tales of Rebirth**

- Saving menu file should not update the XML format
image
image

- Saving skit file should not break the xml format
image
image

- Saving Story file should not break the xml format
image
image

**Review by Mc-muffin — APPROVED** [review]
The changes are minimal, LGTM

**Comment by Mc-muffin** [comment]
~Closing in favor of #74, note that we need to keep features in separate PRs going forward, so this is a one time thing.~
Actually, I think it's better to merge this one and let the other branch catch up.

**Pull request merged**
